version: '3'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=snipr
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/redis
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/postgres