// Code generated by MockGen. DO NOT EDIT.
// Source: shortenedURLReport.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sri-shubham/snipr/storage/models"
)

// MockURLReport is a mock of URLReport interface.
type MockURLReport struct {
	ctrl     *gomock.Controller
	recorder *MockURLReportMockRecorder
}

// MockURLReportMockRecorder is the mock recorder for MockURLReport.
type MockURLReportMockRecorder struct {
	mock *MockURLReport
}

// NewMockURLReport creates a new mock instance.
func NewMockURLReport(ctrl *gomock.Controller) *MockURLReport {
	mock := &MockURLReport{ctrl: ctrl}
	mock.recorder = &MockURLReportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLReport) EXPECT() *MockURLReportMockRecorder {
	return m.recorder
}

// ReportTopDomains mocks base method.
func (m *MockURLReport) ReportTopDomains(ctx context.Context, n int) ([]*models.JSONDomainReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportTopDomains", ctx, n)
	ret0, _ := ret[0].([]*models.JSONDomainReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportTopDomains indicates an expected call of ReportTopDomains.
func (mr *MockURLReportMockRecorder) ReportTopDomains(ctx, n interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportTopDomains", reflect.TypeOf((*MockURLReport)(nil).ReportTopDomains), ctx, n)
}
