name: snipr
host: localhost:8080
port: 8080

shortener:
  minLength: 4
  customMinLength: 7
  customMaxLength: 16

redis:
  host: redis
  port: 6379
  db: 0
  timeout: 5

postgres:
  host: postgres
  port: 5432
  db: snipr
  user: test
  password: test

